# Generated by Django 5.0.6 on 2024-06-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GimnasioWebSite', '0006_maquina_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(choices=[('Piernas', 'Piernas'), ('Pecho', 'Pecho'), ('Brazos', 'Brazos'), ('Espalda', 'Espalda')], max_length=15),
        ),
    ]
