# Generated by Django 5.0.6 on 2024-07-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GimnasioWebSite', '0008_asistencia_cumplimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
