# Generated by Django 5.0.6 on 2024-07-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GimnasioWebSite', '0010_remove_asistencia_nombre_asistencia_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
